### ISSUE TITLE
EDC buildSrc makes it very difficult to use EDC as a subproject

### ISSUE THREAD

**Issue by dcandas** [eclipse-dataspaceconnector/DataSpaceConnector#1293]
# Bug Report

## Describe the Bug
We add EDC as a dependency to our settings.gradle (using includeBuild) to get releases from the main branch as they are added. This is much harder to do since buildSrc folder was added to the project.

### Expected Behavior
EDC can be added as a subproject, just like before buildSrc was added to facilitate plugins.

### Observed Behavior
We get a TurnOffDefaultTasks error when syncing our project using IntelliJ. Here is the [relevant bug tracker](https://youtrack.jetbrains.com/issue/IDEA-276738/Exception-when-importing-project-with-gradle-7-2-No-model-of-typ)

## Steps to Reproduce
Create two projects. Project A should depend on Project B. Project B should depend on EDC. (Use includeBuild.) Syncing these projects cause the error.

- Used version: 
- OS: Windows

## Possible Implementation
We think a possible solution is replacing the buildSrc folder with a plugins project (or a project that is correctly named for this purpose). Then including this project as a submodule or adding the includeBuild(plugins) to the settings.gradle.kts should remove the dependency on buildSrc and fix this issue.
[Composite Builds](https://docs.gradle.org/current/userguide/composite_builds.html)

**Comment by paullatzelsperger** [comment]
The only supported way to use EDC is as Maven/Gradle dependency or set thereof. As we currently are in the process of setting up a MavenCentral deployment, the only way to do it is to publish to `mavenLocal`.
Also, this is not a bug in EDC, if anything, its a bug in IntelliJ.

**Comment by aalldridge** [comment]
To say the least, the way the samples in EDC are set up suggests otherwise. In the absence of releases, we have followed the pattern used there to integrate against EDC.

**Comment by jimmarino** [comment]
The samples are unique given they are part of the EDC repo. At some point, they should probably be pulled out into their own repo and use Maven artifact resolution as well.

I would recommend the approach @paullatzelsperger outlined as that will allow you to switch to using officially published artifacts once our Maven Central integration is complete (which will happen soon).

**Comment by algattik** [comment]
Indeed, here's how we do it:

```

    # Checkout EDC code into DataSpaceConnector directory.
    - name: Checkout EDC
      uses: actions/checkout@v2
      with:
        repository: agera-edc/DataSpaceConnector
        path: DataSpaceConnector
        ref: 8561416a1fbeacca21f574aa56e76a071a287e75 # or main

    # Install Java and cache MVD Gradle build.
    - uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'gradle'

    # Cache EDC packages (installed into ~/.m2) in-between runs.
    # If the latest EDC commit ID has not changed since the last run, this will restore
    # its Maven packages from the cache.
    - name: Cache EDC packages
      uses: actions/cache@v3
      id: cache
      with:
        path: ~/.m2
        # .git/FETCH_HEAD contains latest commit ID
        key: ${{ runner.os }}-m2-${{ hashFiles('DataSpaceConnector/.git/FETCH_HEAD') }}

    # Install EDC packages into ~/.m2.
    # This action only runs if the packages could not be restored from the cache.
    - name: Build EDC packages
      run: |
        ./gradlew publishToMavenLocal
      if: steps.cache.outputs.cache-hit != 'true' # only on cache miss
      shell: bash
      working-directory: DataSpaceConnector

    - name: Delete EDC packages
      run: rm -r DataSpaceConnector
      shell: bash
```
