### ISSUE TITLE
exclude docs folder from running tests 

### ISSUE THREAD

**Issue by MoritzKeppler** [eclipse-dataspaceconnector/DataSpaceConnector#893]
If a PR just contains changes to documentation we could skip most of the automated checks.

## Which Areas Would Be Affected?
CI

## Why Is the Feature Desired?
faster builds

## Solution Proposal
Exclude docs folder in gh actions files, e.g.
```
on:
  push:
    paths-ignore:
      - 'docs/**'
```

## Type of Issue
minor improvement
