### ISSUE TITLE
Activate Dependabot

### ISSUE THREAD

**Issue by DominikPinsel** [eclipse-dataspaceconnector/DataSpaceConnector#906]
# Feature Request

Enable the Dependabot  tool to keep our libraries and GitHub Actions automatically up to date and get alerts in case there is a known vulnerability.

## Which Areas Would Be Affected?

Dependabot is able to scan our projects dependencies daily and creates pull-requests by itself.

## Why Is the Feature Desired?

This would increase the security of the EDC.

## Solution Proposal

I've set up a sample repository with a generated pull-request from Dependabot.
https://github.com/DominikPinsel/dependabot-demo

Getting Dependabot in the repository is pretty straight forward.

### 1. Enable Dependabot in the repository security settings

![image](https://user-images.githubusercontent.com/20866918/158555391-f59bd979-cbe9-4544-a742-ec1ce66e6c51.png)

### 2. Create  `.github/dependabot.yaml`

```yaml
# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      # Prefix all commit messages with "github-actions"
      prefix: "github-actions"
      include: "scope"
      
  - package-ecosystem: "maven" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    commit-message:
      # Prefix all commit messages with "maven"
      prefix: "maven"
      include: "scope"
```

## Type of Issue

Security Improvement

## Checklist

- [x] assigned appropriate label?
- [x] **Do NOT select a milestone or an assignee!**

<sub>Dominik Pinsel <dominik.pinsel@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md) </sub>
